### PR TITLE
Update configuration.adoc

### PR DESCRIPTION
**Pull request by marsjoy**
Spelling correction of 'peform' to 'perform'

Thank you for submitting a pull request! 

Please make sure you have signed our [Contributor License Agreement (CLA)][].  
We are not asking you to assign copyright to us, but to give us the right to distribute your code without restriction. We ask this of all contributors in order to assure our users of the origin and continuing existence of the code.  
You only need to sign the CLA once.

- [x ] I have signed the [Contributor License Agreement (CLA)][]

[Contributor License Agreement (CLA)]: https://www.elastic.co/contributor-agreement/

### CODE REVIEW

**Comment by jbaiera** [comment]
Thanks for opening a PR! Have you been able to sign the CLA yet?

**Comment by marsjoy** [comment]
@jbaiera Yes, I signed it and confirmed. :)

**Comment by jbaiera** [comment]
@marsjoy It seems that the email address that authored the commit does not match your email address on file that has signed the CLA. Can you please add both emails to your Github profile (they can be hidden) so we can correctly match your signature to your Github account and the Git commit?

**Comment by jbaiera** [comment]
I just saw that this is green now. LGTM! Thanks!

**Pull request merged**
