### PR TITLE
Update configuration.adoc

### PR DESCRIPTION
**Pull request by cbc666**
Thank you for submitting a pull request! 

Please make sure you have signed our [Contributor License Agreement (CLA)][].  
We are not asking you to assign copyright to us, but to give us the right to distribute your code without restriction. We ask this of all contributors in order to assure our users of the origin and continuing existence of the code.  
You only need to sign the CLA once.

- [ ] I have signed the [Contributor License Agreement (CLA)][]

[Contributor License Agreement (CLA)]: https://www.elastic.co/contributor-agreement/

### CODE REVIEW

**Comment by masseyke** [comment]
Thanks for the PR. Did you run into problems not giving `http://`? I thought it would work either way, but have not tried it out recently.

**Comment by cbc666** [comment]
if not given http:// it works,but if not given https://,it goes wrong. i tried many times to find theproblem.so i adjust to change the doc.
thanks a lot



 ----------------------------------------------------------------------------
曹璐
电话：+86-152 0115 8527
Email: ***@***.***






---- Replied Message ----
| From | Keith ***@***.***> |
| Date | 11/09/2022 00:00 |
| To | ***@***.***> |
| Cc | ***@***.******@***.***> |
| Subject | Re: [elastic/elasticsearch-hadoop] Update configuration.adoc (PR #2038) |

Thanks for the PR. Did you run into problems not giving http://? I thought it would work either way, but have not tried it out recently.

**Comment by jbaiera** [comment]
I'm going to close this out because it's been a long while - I don't think this is necessary to include in the logs. I'd rather get to the bottom for why it does not work without the scheme. When the client denotes that SSL is enabled it should automatically prefix URL's with `https://`

**Comment by cbc666** [comment]
automatically prefix URL's with https:// is a good idea

**Pull request closed without merging**
