### PR TITLE
Updating latest Spark version

### PR DESCRIPTION
**Pull request by mharkins-spokeo**
Hope I'm doing this right.  Documentation claims 1.6.2 is the latest Spark release, but Apache indicates it's 2.2.0.

Thank you for submitting a pull request! 

Please make sure you have signed our [Contributor License Agreement (CLA)][].  
We are not asking you to assign copyright to us, but to give us the right to distribute your code without restriction. We ask this of all contributors in order to assure our users of the origin and continuing existence of the code.  
You only need to sign the CLA once.

- [x] I have signed the [Contributor License Agreement (CLA)][]

[Contributor License Agreement (CLA)]: https://www.elastic.co/contributor-agreement/

### CODE REVIEW

**Comment by mharkins-spokeo** [comment]
Missed the checkbox.  I have signed the CLA.

**Comment by jbaiera** [comment]
Hi @mharkins-spokeo, thanks for opening a PR. Could you target your changes against master? It's easier for us to backport than forwardport changes.

**Comment by mharkins-spokeo** [comment]
Targeted to master.

**Comment by jbaiera** [comment]
It looks like you pulled up a good number of commits in retargetting to master. You might have to rebase your branch _onto_ master for it to pick up the retargetting correctly.

**Comment by mharkins-spokeo** [comment]
I'll close this PR and retry.

**Pull request closed without merging**
