### PR TITLE
encodes : and | when using them in url

### PR DESCRIPTION
**Pull request by bwf93**
Thank you for submitting a pull request! 

Please make sure you have signed our [Contributor License Agreement (CLA)][].  
We are not asking you to assign copyright to us, but to give us the right to distribute your code without restriction. We ask this of all contributors in order to assure our users of the origin and continuing existence of the code.  
You only need to sign the CLA once.

- [ X] I have signed the [Contributor License Agreement (CLA)][]

[Contributor License Agreement (CLA)]: https://www.elastic.co/contributor-agreement/

### CODE REVIEW

**Comment by jbaiera** [comment]
I think the CLA is just a little slow on the uptake. Hopefully it will refresh.

**Comment by jbaiera** [comment]
Looks like it hasn't updated yet. I'll see what's going on.

**Comment by megri** [comment]
I don't think this should be merged. Please see comment on #874

**Comment by jbaiera** [comment]
@megri The issue that this PR is solving is a `org.apache.commons.httpclient.URIException: Invalid query`, which is thrown during the URI parsing before the request is even sent to Elasticsearch. I am thinking this has to do with an unsupported version of commons httpclient. That being said, I think that this is still a win if it means that a simple encoding change will allow a different client version to just work, even if it's not officially supported.

**Comment by karmi** [comment]
Hi @bwf93 , we have your CLA signature on file, but with a different e-mail. Can you please add both to your Github profile (they can be hidden) so we can correctly match your signature to your Github account and the Git commit?

**Comment by jbaiera** [comment]
Due to time constraints surrounding backwards compatibility testing, I elected to implement a fix for #874 in commit https://github.com/elastic/elasticsearch-hadoop/commit/d442bb4479c2ae8478a10f25a7f0edb6b7256d87. The commit should catch the issues referenced in this PR. Because of this, the PR is no longer needed, and will be closed.

**Pull request closed without merging**
