### PR TITLE
Change configuration order

### PR DESCRIPTION
**Pull request by JamesLuoau**
Have swapped the config order of "es.ser.writer.value.class" & "es.ser.reader.value.class" to match the correct description.

### CODE REVIEW

**Comment by costin** [comment]
Can you please sign the CLA? Thanks,

**Comment by JamesLuoau** [comment]
Hi, Costin, Yes I did sign the CLA as name "Pinghua Luo", sorry for the confuse names.

**Comment by costin** [comment]
The CLA needs to be signed with the same email as the one used by in the
github commits/PR. Otherwise, there's no way to track down the commits to
the CLA.
Can you please either rebase your commit (with the CLA address) or sign
another CLA with the correct email?

Thanks,

**Comment by JamesLuoau** [comment]
Double checked my signed CLA copy and both email / github user name match with my commit details, could you please have a check and let me know what's wrong. Thank you.

**Comment by JamesLuoau** [comment]
i signed with my other email as well, hopefully it works.

**Comment by costin** [comment]
Merged in master (d0d8c94b07328b3929c6184c4bd2ac21b37e04a8).

Thanks,

**Pull request closed without merging**
