### PR TITLE
corrected link to 'ADD' command

### PR DESCRIPTION
**Pull request by sreev**
Thank you for submitting a pull request! 

Please make sure you have signed our [Contributor License Agreement (CLA)][].  
We are not asking you to assign copyright to us, but to give us the right to distribute your code without restriction. We ask this of all contributors in order to assure our users of the origin and continuing existence of the code.  
You only need to sign the CLA once.

- [X] I have signed the [Contributor License Agreement (CLA)][X]

[Contributor License Agreement (CLA)]: https://www.elastic.co/contributor-agreement/

Link of 'ADD' command, modified,
From: https://cwiki.apache.org/Hive/languagemanual-cli.html#LanguageManualCli-HiveResources
To: https://cwiki.apache.org/confluence/display/Hive/LanguageManual+Cli#LanguageManualCli-HiveResources

### CODE REVIEW

**Comment by sreev** [comment]
i signed the CLA when suggested the 'create pull request' suggested.  from git it took me to CLA site and i verified from my inbox.  seems it didn't make in time when the above 'checks' ran.

**Comment by sreev** [comment]
was in failed state. closed and re-opened, to trigger 'checks', again. CLA check now goes thru.
the travis-ci failing for someother scala file error.

possibility of optimizing, here, when the 'change/pull request' is in 'documentation'.

**Comment by jbaiera** [comment]
The CI check has been on the fritz for a while on branches with non `SNAPSHOT` project versions. This was fixed last week. Pulled the changes down locally and they look good to me. Thanks for the PR!

**Comment by jbaiera** [comment]
Cherrypicked to `master` and `2.x` branches.

**Pull request closed without merging**
