### PR TITLE
add EsInputSplit.toString method which can be used for debugging

### PR DESCRIPTION
**Pull request by wankunde**
- [x] I have signed the [Contributor License Agreement (CLA)[]

When we debug the mapreduce program, EsInputSplit's detail message will tell us what the map is doing.

### CODE REVIEW

**Comment by jbaiera** [comment]
This LGTM, but it seems that the CLA is either not signed or hasn't updated yet. Could you double check that you have signed the CLA?

**Comment by wankunde** [comment]
@jbaiera I'm sorry, i have just signed the CLA,and got a license agreement.

**Comment by karmi** [comment]
@wankunde , all good now, thanks!

**Comment by wankunde** [comment]
thank you all~~

**Comment by jbaiera** [comment]
Awesome, thanks @wankunde @karmi

**Pull request merged**
