### PR TITLE
elasticsearch update doc

### PR DESCRIPTION
**Pull request by cclient**
update support 
`{
  "upsert": {},
  "doc": {...}
}`

demo
`case class ES_Upsert(kw_index: String, kw_type: String, id: String, date_idate: String, date_udate: String)`
`case class ES_Doc(date_udate: String)`
`case class ES_UpsertDoc(upsert: ES_Upsert, doc: ES_Doc)`

`  .saveToEs(Map[String, String](
      "es.resource" -> "{upsert.kw_index}/{upsert.kw_type}",
      "es.nodes" -> es,
      "es.input.json" -> "false",
      "es.update.doc" -> "true",
      "es.write.operation" -> "upsert",
      "es.mapping.exclude" -> "upsert.kw_index,upsert.kw_type,upsert.id",
      "es.mapping.id" -> "upsert.id"
    ))`

### CODE REVIEW

**Comment by jbaiera** [comment]
@cclient It seems that this PR is not completed? Will you be working on it further? One thing to keep in mind is that sending upserts versus updates is a feature all integrations use. This will need to work for frameworks other than Spark.

**Comment by cclient** [comment]
@jbaiera Forgive my poor english,I only tested in spark,and won't working for other integrations, just wish it may be help for somebody who need '{ "upsert": {}, "doc": {...} }''

**Comment by jbaiera** [comment]
@cclient We appreciate your willingness to help push the project forward. As described in #553, this issue affects all users for ES Hadoop. Unfortunately, we cannot accept a PR that only solves this problem for only a single integration. If you are willing to put work into a solution for the other integrations we can keep this PR open and move forward.

**Comment by jbaiera** [comment]
Closing this out as it does not look like there will be further work applied to it. Happy to re-open if that changes.

**Pull request closed without merging**
