### PR TITLE
Add support for Spark integration on Scala 2.12

### PR DESCRIPTION
**Pull request by jbaiera**
This PR adds Scala 2.12 to the list of supported runtimes for the Spark integration. To use Scala 2.12 support, the `elasticsearch-spark-20_2.12` artifact id should be used when downloading dependencies. The default level of support included in the project wide zip archive and the project wide uber jar will remain Scala 2.11 for the time being. Eventually the default version in 8.0 will be updated to a more recent version of Spark/Scala.

### CODE REVIEW

**Comment by jbaiera** [comment]
fixes #1224

**Review by danhermann — APPROVED** [review]
LGTM!

**Comment by VladZabolotnyV** [comment]
@jbaiera Looks like `elasticsearch-spark-20_2.12` is missing in [Maven repository](https://mvnrepository.com/artifact/org.elasticsearch/elasticsearch-spark-20) along with `7.12.0` version. Was it not published for some reason?

**Comment by jbaiera** [comment]
@VladZabolotnyV Version 7.12.0 has not been released yet. I'll be getting the artifact wired up for the daily snapshot builds in the mean time.

**Comment by monkey-typewriter** [comment]
Hey guys,
Any progress on this ?

thanks

**Comment by jbaiera** [comment]
@monkey-typewriter The work is completed and will be released in 7.12. You can get early access to the changes for testing purposes by pulling a nightly snapshot, though I would advise against using that version in production as it is not yet generally available.

**Comment by VladZabolotnyV** [comment]
@jbaiera when the 7.12 release is planned to happen?

**Comment by jbaiera** [comment]
@VladZabolotnyV I unfortunately don't have an official concrete date for the 7.12 GA release. Sorry! Hopefully it will land soon!

**Pull request merged**
