### PR TITLE
Support for custom MetadataExtractor within Spark flows

### PR DESCRIPTION
**Pull request by nerdynick**
Changes:
* Add support for a user defined MetadataExtractor within Spark. Also includes support for SettingsAware MetadataExtractor classes. 
* Expands the MetadataExtractor interface to recieve the Metadata Object during their work flow. 
* PerEntityPoolingMetadataExtractor expanded to support it's reuse within user defined MetadataExtractors.

Thank you for submitting a pull request! 

Please make sure you have signed our [Contributor License Agreement (CLA)][].  
We are not asking you to assign copyright to us, but to give us the right to distribute your code without restriction. We ask this of all contributors in order to assure our users of the origin and continuing existence of the code.  
You only need to sign the CLA once.

- [x] I have signed the [Contributor License Agreement (CLA)][]

[Contributor License Agreement (CLA)]: https://www.elastic.co/contributor-agreement/

### CODE REVIEW

**Comment by jbaiera** [comment]
@nerdynick Is there an issue open for this? I'm not sure what the goal is here entirely. I can start reviewing it, but knowing what you're looking for here will help with the review process.

**Comment by nerdynick** [comment]
@jbaiera No issue open. The basic goal was to allow users to also be able to provide MetadataExtractor's similar to how they can Index/Field Extractor's. The surrounding changes where in support for expanding the nature of MetadataExtractor to support user defined ones better. 

The use case I had was to be able to provide ESSpark with a Tuple2 where item 1 is an index pattern instead of the actual index and allowing that index pattern to be cached in a pool. The only way to gain that much level of control and information needed is by changing out the MetadataExtractor as the IndexExtractors do not have access to the Tuple2->item1 data. 

The only way I could see around this was hackie and would have involved mapping exclusions and overloading the value with more information to be thrown away. This just seemed simple and opened up more avenues for users to solve more complex use cases. 

Something I also noticed for another issue would be to move the Json transform layer into a MetdataExtractor instead of baking it in like it is currently. Seems like they are trying to achieve the same things but adding a whole bunch more layers to the mix to support the separation.

**Comment by jbaiera** [comment]
I'm not entirely sold on this PR to be honest. After working on the new error handlers, its clear how much work it is to maintain these sorts of internal API's. We do not consider these interfaces to be a part of the public API for the connector, and thus they are not protected from breaking changes in between major releases as per semantic versioning rules. I feel like it would be incredibly trappy to expose them further.

**Comment by nerdynick** [comment]
This PR is only exposing 1 more Extractor then is already exposed. As Field, Index, and Byte extractors are already exposed. As well as given the code that is/was already in place around MetadataExtractor it looked like the intent was already there with the Interface's existence and only 1 inheritance tree created (ScalaMetadataExtractor->PerEntityPoolingMetadataExtractor->MetadataExtractor).

I think an argument could be made for further exposing the use of PerEntityPoolingMetadataExtractor. But not to expose MetadataExtractor and its usage seems kinda limiting in the amount of gained support for a user to be able to optimize their pipelines flows and get the best performance out of it. With this PR I was able to better optimize and reduce each flow by 1-2sec per 10sec batch on SparkStreaming. As before I was having to do filter/split of data to 2 separate ES-Hadoop instance to achieve the same effect. This saved me from having to write my own Index Pattern logic. As well as still maintain isolation of all the logic around ES into one central ES layer instead of trying to weave it into my parse/transform layers.

**Pull request merged**
