### PR TITLE
fixed reference to maven dependency

### PR DESCRIPTION
**Pull request by Gschiavon**
Fixed wrong reference to maven central

### CODE REVIEW

**Comment by jbaiera** [comment]
This LGTM, but it seems the CLA checker is failing. Have you signed our Contributor License Agreement?

**Comment by Gschiavon** [comment]
Yes I did, but after doing the PR... so I think it need to refresh somehow? 
Regards.

**Comment by jbaiera** [comment]
@Gschiavon Often times the CLA checker will fail if you sign it with an email address that isn't the same as the one on your github account.

**Comment by Gschiavon** [comment]
True, Ive signed it with the same email address now :)

**Comment by jbaiera** [comment]
I'll give the PR a quick chance to update, and if not I'll dig into what's up with the CLA checker.

**Comment by jbaiera** [comment]
@Gschiavon The issue here is that the author information on your commit does not match your github information, and thus it cannot be validated. I would fix this with a `git commit --amend --reset-author` and force push it to your branch.

**Comment by Gschiavon** [comment]
Done @jbaiera, I did git commit --amend --author="Author name <email@address>"  then push to my branch. 

Thanks.

**Comment by jbaiera** [comment]
@Gschiavon awesome, thanks! And thank you for the contribution!

**Pull request merged**
