### PR TITLE
[DOCS] Add 8.0.0-rc2 release notes

### PR DESCRIPTION
**Pull request by jrodewig**
### Preview
https://elasticsearch-hadoop_1892.docs-preview.app.elstc.co/guide/en/elasticsearch/hadoop/master/eshadoop-8.0.0-rc2.html

### CODE REVIEW

**Comment by jrodewig** [comment]
@elasticmachine update branch

**Comment by masseyke** [comment]
Do we usually put major deprecation information (#1845) into the release notes? Or is the breaking changes section enough?

**Comment by jrodewig** [comment]
> Do we usually put major deprecation information (#1845) into the release notes? Or is the breaking changes section enough?

#1845 should be in the RNs too. I likely fumbled something in my original GitHub filter. Thanks for catching this.

Added with https://github.com/elastic/elasticsearch-hadoop/pull/1892/commits/8e4f1deb0e44eb693e568ad855a8e6d3237b68d5.

Here's a link to the GH filter I used for this round: https://github.com/elastic/elasticsearch-hadoop/pulls?q=is%3Apr+label%3Av8.0.0-rc2+is%3Aclosed+-label%3Anon-issue+-label%3Abackport+-label%3A%3Edocs+

**Review by masseyke — APPROVED** [review]
LGTM

**Pull request merged**
