### PR TITLE
Set X-Opaque-ID header in request header

### PR DESCRIPTION
**Pull request by masseyke**
Adding an X-Opaque-ID header to bulk requests from mapreduce, spark, and hive so that index requests from
elasticsearch-hadoop can be tracked in the tasks api, the slowlog, and the deprecations log.
Relates #1182

### CODE REVIEW

**Comment by jbaiera** [comment]
Do we have a good idea of what is present in the task attempt id? I imagine that it's mostly book keeping information about the currently executing task, but not much about the job itself? I wonder if we should also see about pulling in the application name from the job settings for the opaque id as well?

**Comment by jbaiera** [comment]
As for testing, I think we might be able to make this work with some unit testing primarily. Likely some test cases for each of the integrations with new code to make sure that they capture the task id/application info correctly, and a test for the client against some mocked http library objects to make sure it adds the header correctly?

**Comment by masseyke** [comment]
> Do we have a good idea of what is present in the task attempt id? I imagine that it's mostly book keeping information about the currently executing task, but not much about the job itself? I wonder if we should also see about pulling in the application name from the job settings for the opaque id as well?

I believe for mapreduce jobs the taskAttemptId includes the job/application id (I need to confirm that though). The job name might also be useful. I'm not sure how verbose we want to get here, although there's only one of these per bulk request so I guess it won't take up that much bandwidth.
For spark the taskAttemptId is only a number like "3", so I included the applicationId as well.

**Comment by jbaiera** [comment]
> I'm not sure how verbose we want to get here, although there's only one of these per bulk request so I guess it won't take up that much bandwidth.

I wonder if we should include the X-Opaque-Id on all requests sent to ES? The driver program can launch some searches that can easily get heavy in the planning phase that might be good to have tagged with client info.

**Comment by jbaiera** [comment]
Should probably let users give their own opaque ids as well, override it with the job name if it's not set? Append the task id on the end of it if it's set.

**Comment by masseyke** [comment]
Closing this one in favor of #1770, which is much simpler and more complete.

**Pull request closed without merging**
