### PR TITLE
Fix setup httpProxy property

### PR DESCRIPTION
**Pull request by wmellouli**
Thank you for submitting a pull request! 

Please make sure you have signed our [Contributor License Agreement (CLA)][].  
We are not asking you to assign copyright to us, but to give us the right to distribute your code without restriction. We ask this of all contributors in order to assure our users of the origin and continuing existence of the code.  
You only need to sign the CLA once.

- [x] I have signed the [Contributor License Agreement (CLA)][]

[Contributor License Agreement (CLA)]: https://www.elastic.co/contributor-agreement/

### CODE REVIEW

**Comment by jbaiera** [comment]
Thanks for opening a PR @wmellouli, but could you update the post with a synopsis for the changes?

**Comment by wmellouli** [comment]
### Issue description

When can't disable the use of system Http proxy properties (http.proxyHost and http.proxyPort) using  the property **es.net.proxy.http.use.system.props**. As a workaround, we have to use the **https** property **es.net.proxy.https.use.system.props**.

In line 410 of class org.elasticsearch.hadoop.cfg.Settings, we load **HTTPS** properties instead of **HTTP** properties: 
[org.elasticsearch.hadoop.cfg.Settings#Line410][]



### Steps to reproduce

Set an http proxy in your system, and then try to disable the use of system Http proxy properties:

```
es.net.proxy.http.use.system.props = false
```

this property should not have an effect. 

As a workaround, when you use the **https** property instead:

```
es.net.proxy.https.use.system.props = false
```
now, it should work.

[org.elasticsearch.hadoop.cfg.Settings#Line410]: https://github.com/elastic/elasticsearch-hadoop/blob/master/mr/src/main/java/org/elasticsearch/hadoop/cfg/Settings.java#L410

**Comment by wmellouli** [comment]
@jbaiera I added the Issue description and steps to reproduce

**Comment by jbaiera** [comment]
@wmellouli Awesome, thanks. The change looks good to me. Good find.

**Pull request merged**
