### PR TITLE
[#754][#743] update to compat with storm 1.x.x

### PR DESCRIPTION
**Pull request by mazhechao**
The most change is that the package name changes from backtype to org.apache, and just fix that.

### CODE REVIEW

**Comment by mazhechao** [comment]
@costin  Will you have a look at it please?

**Comment by costin** [comment]
Thanks @mazhechao 
As I've mentioned in #754, I'm torn on whether to upgrade to Storm 1.0 or keep 0.9 around for a while. A compromise might be to upgrade master (5.0.0) to Storm 1.0 and direct Storm users of 0.9 to 2.x

**Comment by mazhechao** [comment]
I agree to upgrade master(5.0.0) to Storm 1.0, as there are many Storm users using 0.9.x now.

I notice that storm-elasticsearch has been merged into Storm project since 1.0.0. However storm-ealsticsearch doesn't support ES 2.x now. As a result, those who use storm-elasticsearch cannot use ES 2.x. If es-hadoop supports Storm 1.0, users can use both new Storm and ES at the same time.

**Comment by costin** [comment]
This has been merged into master (upcoming 5.0-alpha3).
Several things to note:
1. the PR was not complete and the code did not compile (the guava classes in Storm had been moved to a different package as well).
2. Storm 1.x also depends on log4j2 instead of log4j 1 and is not really compatible. Since ES and the rest of the libraries do depend on log4j 1 resolving this was somewhat problematic. I saw you tried to resolve the conflict in the classpath but that only worked for Storm while breaking all the other libraries. However removing the conflicting slf4j api seems to be solved the issue.

Last but not least the integration tests are failing with Storm 1.x. It's the same old problem of race conditions and concurrency - starting the topology and waiting for tuple ingestion is not easy since Storm doesn't offer any utility classes (as far as I know) and while the tests do pass in isolation, in bulk things start to trip.
I've tweaked them a bit but it doesn't seem to be enough - I've raised a separate issue for this. Going forward I'm seriously thinking of moving to unit tests since each release of Storm seems to break things a bit in this department.

@mazhechao Thank for your contribution and hopefully there will be many more in the future! Cheers!

**Comment by mazhechao** [comment]
@costin Thanks for your review and comment.

**Pull request closed without merging**
