### PR TITLE
Update spark.adoc

### PR DESCRIPTION
**Pull request by nicolasguyomar**
When I try to insert JSON that contains breaklines (I was on a Windows env), resulting Mapping does not contains my fields, I only end up with the JSON content in the source field : 
{"_index":"spark","_type":"json-xxx","_id":"myId","_score":1.0,"_source":{"field1" : 1, "field2" : "2"}}

Thank you for submitting a pull request! 

Please make sure you have signed our [Contributor License Agreement (CLA)][].  
We are not asking you to assign copyright to us, but to give us the right to distribute your code without restriction. We ask this of all contributors in order to assure our users of the origin and continuing existence of the code.  
You only need to sign the CLA once.

- [x] I have signed the [Contributor License Agreement (CLA)][]

[Contributor License Agreement (CLA)]: https://www.elastic.co/contributor-agreement/

### CODE REVIEW

**Comment by jbaiera** [comment]
Sorry for the late response. Have you signed the CLA? This change LGTM otherwise.

**Comment by nicolasguyomar** [comment]
Hi,

Yes I did signed the CLA concurrently while submitting this PR, thus the first failed attempt for the build

Thank you !

**Comment by jbaiera** [comment]
All good! Can you please address the above comments?

> Can you change this PR to merge into master?

**Comment by jbaiera** [comment]
It looks like your branch change broke the PR pretty badly. Perhaps you should rebase the changes for your branch on to master and re-open a new PR.

**Pull request closed without merging**
