### PR TITLE
add scaled and half float to schemautils (#981)

### LINKED ISSUE #981: Half and scaled floats missing from spark 2 schema
### What kind an issue is this?

Bug report.

### Issue description

Type mapping for scaled and half floats is missing for spark 2 sql. Issue #822 is the original issue where the schema mapping was added, looks like this file was missed.

### Steps to reproduce

If you attempt to work with any index that uses scaled or half floats using spark 2 you can reproduce the issue. Using metricbeat is a good example as it makes extensive use of scaled floats.

### Version Info

OS:         :  Amazon Linux (4.4.35-33.55.amzn1.x86_64)
JVM         :  openjdk 1.8.0_121
Hadoop/Spark:  2.7.3-amzn-1
ES-Hadoop   :  5.2.3 (issue still exists in master)
ES          :  5.2.1

### PR DESCRIPTION
**Pull request by mdelaney**
fixes #981
spark-sql-20 was missed when this was first added

Thank you for submitting a pull request! 

Please make sure you have signed our [Contributor License Agreement (CLA)][].  
We are not asking you to assign copyright to us, but to give us the right to distribute your code without restriction. We ask this of all contributors in order to assure our users of the origin and continuing existence of the code.  
You only need to sign the CLA once.

- [x] I have signed the [Contributor License Agreement (CLA)][]

[Contributor License Agreement (CLA)]: https://www.elastic.co/contributor-agreement/

### CODE REVIEW

**Comment by mdelaney** [comment]
About the CLA check failure above... My understanding is that Tubular Labs (the company I work for) has signed the CLA. Is there anything else that needs to be done?

**Comment by jbaiera** [comment]
@karmi Would you be able to comment on the CLA issue here? My understanding right now is that the email address on the contributions needs to be in the database as having signed, but if a different email is used then the user needs to add the email address that signed the CLA to their Github profile. Is this correct?

**Comment by mdelaney** [comment]
I may be able to shed some light on the CLA issue. It seems our CEO signed two CLA agreements, one with our github usernames and one without. I wonder if that may be the problem?

**Comment by jbaiera** [comment]
@mdelaney I'd like to get this merged, but the CLA check is a bit of a road block. After speaking with some of our infra folks their response was that we don't fetch Corporate CLA signatures. You'll need to individually sign the CLA with the email address on your Github account for the check to pass.

**Comment by mkamprath** [comment]
@jbaiera Just a CLA logistical question (I am on the one who coordinated the signature): What is the purpose of the Corporate CLA then? Do the individuals have to further sign the "individual contributing under an existing company contributor agreement"?

**Comment by karmi** [comment]
Hello @mkamprath, the Corporate CLA is perfectly fine for us to handle, it's just that the "Individual" CLAs are simpler to process. We have looked into our records, but can't find any record related to Tubular Labs or your name -- can you please forward the e-mail you have received upon signature to [my e-mail](karel.minarik@elastic.co) so I can try looking it up?

**Comment by mkamprath** [comment]
@karmi  thanks, I just sent the CLA to your email.

**Comment by karmi** [comment]
Thanks for the e-mail, @mkamprath! I've found your e-mail in our records indeed.

The misunderstanding from yesterday is coming from the fact that I forgot that we have a third option on agreement page, the _An individual contributing under an existing company contributor agreement_:

corporate-cla-individual

This is to "confirm" the signature for each listed person, and these signatures _are_ then automatically fetched to our systems (as opposed to the agreement between Elastic and the company itself).

Is it all right for you to sign the agreement under that particular option, @mdelaney?

**Comment by mdelaney** [comment]
@karmi - Thanks! I've just signed the CLA.

Is there anything else I need to do on my end or are we good to go?

**Comment by karmi** [comment]
@mdelaney Everything green, many thanks for the understanding and cooperation!

**Comment by jbaiera** [comment]
Thanks @karmi, @mdelaney, and @mkamprath!

**Pull request merged**
