### PR TITLE
Update Gradle wrapper from 8.1 to 8.1.1

### PR DESCRIPTION
**Pull request by breskeby**
keep in sync with ES gradle wrapper version

### CODE REVIEW

**Comment by jbaiera** [comment]
LGTM - though green CI might be blocked on #2081 / #2083

**Comment by jbaiera** [comment]
@breskeby should be good for a retry with the latest changes

**Comment by breskeby** [comment]
@jbaiera pushed a rebase

**Review by jbaiera — APPROVED** [review]
LGTM - CI is upset about not having snapshot builds yet, so feel free to merge whenever

**Pull request closed without merging**
