### PR TITLE
Replacing the use of Java object serialization with Jackson

### PR DESCRIPTION
**Pull request by masseyke**
We use ObjectOutputStream/ObjectInputStream serialization/deserialization internally for several classes in es-hadoop. This switches to jackson serialization/deserialization to/from json strings instead.

### CODE REVIEW

**Comment by masseyke** [comment]
@elasticmachine run elasticsearch-ci/hadoop-check

**Review by jbaiera — APPROVED** [review]
LGTM pending green CI

**Comment by masseyke** [comment]
@elasticmachine run elasticsearch-ci/hadoop-check

**Comment by masseyke** [comment]
@elasticmachine update branch

**Comment by jbaiera** [comment]
@elasticmachine run elasticsearch-ci/hadoop-check

**Pull request merged**
