### PR TITLE
Throw clean exception if query is not well formed

### PR DESCRIPTION
**Pull request by ebuildy**
- [x] I have signed the [Contributor License Agreement (CLA)][]

[Contributor License Agreement (CLA)]: https://www.elastic.co/contributor-agreement/

To avoid "NullPointerException" if query is not a valid ressource, could help people to understand whats happened.

### CODE REVIEW

**Comment by jbaiera** [comment]
+1 Thanks for the PR!

**Comment by jbaiera** [comment]
Actually, could you port this change over to the 5.0 branch?

**Comment by ebuildy** [comment]
Sure, should be not a big deal ^^

**Comment by jbaiera** [comment]
Thanks for the PR! I'm closing this as a duplicate. Change was merged on #866

**Comment by ebuildy** [comment]
Cool! Thanks

**Pull request closed without merging**
