### PR TITLE
Update Spark doc for new API InputFormat

### PR DESCRIPTION
**Pull request by MLnick**
Issue: #390

### CODE REVIEW

**Comment by costin** [comment]
@MLnick can you please sign the CLA?

**Comment by MLnick** [comment]
have signed it - not sure how long it takes to come through

**Comment by costin** [comment]
It might be an issue on our side. thanks for confirming.

**Comment by costin** [comment]
Cherry-picked in master through ec7ba947d74cad09046688bc36a95f4c0566681b Did it by hand for 2.x due to conflicts.

**Pull request closed without merging**
