### PR TITLE
Fix example for spark.

### PR DESCRIPTION
**Pull request by withccm**
See issue #767

### CODE REVIEW

**Comment by withccm** [comment]
I am Signed and Filed. But I'm not finished Contributor Agreement. 
Can you check my signed License, plz?

**Comment by karmi** [comment]
Hi @withccm, we have found your signature in our records, but it seems like you have signed with a different e-mail than the one used in yout Git [commit](https://github.com/elastic/elasticsearch-hadoop/pull/768.patch). Can you please add both of these e-mails into your Github profile (they can be hidden), so we can match your e-mails to your Github profile?

**Comment by withccm** [comment]
Hello. @karmi , I committed with a different email. Thank you.

**Comment by karmi** [comment]
Great, @withccm, the CLA is now passing -- thanks!

**Comment by costin** [comment]
@withccm Thanks! Merged in master in 2.x. Cheers!

**Comment by withccm** [comment]
@costin Thanks! Have a nice day!

**Pull request closed without merging**
